baseURL = 'https://sciolyatuva.org/'
languageCode = 'en-us'
title = 'Science Olympiad at UVA'
enableGitInfo = true
disableKinds = ["section", "taxonomy", "term", "RSS"]

[params]
email = 'sciolyatuva@gmail.com'
# alert = 'In light of the recent shooting at the University of Virginia, the 2022 Science Olympiad at UVA Invitational has been canceled. [Learn more](/tournaments#cancellation-notice)'
